[2024-05-23T17:54:57.680+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T17:54:57.725+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_guess.guess_number scheduled__2023-03-01T12:15:00+00:00 [queued]>
[2024-05-23T17:54:57.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_guess.guess_number scheduled__2023-03-01T12:15:00+00:00 [queued]>
[2024-05-23T17:54:57.743+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-23T17:54:57.780+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): guess_number> on 2023-03-01 12:15:00+00:00
[2024-05-23T17:54:57.792+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3797) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T17:54:57.795+0000] {standard_task_runner.py:63} INFO - Started process 3804 to run task
[2024-05-23T17:54:57.796+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xcom_guess', 'guess_number', 'scheduled__2023-03-01T12:15:00+00:00', '--job-id', '1455', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmplbbrox3d']
[2024-05-23T17:54:57.798+0000] {standard_task_runner.py:91} INFO - Job 1455: Subtask guess_number
[2024-05-23T17:54:57.827+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-23T17:54:57.898+0000] {task_command.py:426} INFO - Running <TaskInstance: xcom_guess.guess_number scheduled__2023-03-01T12:15:00+00:00 [running]> on host 88d46e04e9cd
[2024-05-23T17:54:58.094+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xcom_guess' AIRFLOW_CTX_TASK_ID='guess_number' AIRFLOW_CTX_EXECUTION_DATE='2023-03-01T12:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-01T12:15:00+00:00'
[2024-05-23T17:54:58.095+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T17:54:58.144+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T17:54:58.168+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sample_dag.py", line 19, in guess_number
    raise AirflowException(f"Wrong guess! Number: {number}, guess: {guess}")
airflow.exceptions.AirflowException: Wrong guess! Number: 2, guess: 7
[2024-05-23T17:54:58.177+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=xcom_guess, task_id=guess_number, run_id=scheduled__2023-03-01T12:15:00+00:00, execution_date=20230301T121500, start_date=20240523T175457, end_date=20240523T175458
[2024-05-23T17:54:58.201+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1455 for task guess_number (Wrong guess! Number: 2, guess: 7; 3804)
[2024-05-23T17:54:58.253+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T17:54:58.273+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
