[2024-05-23T17:50:20.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T17:50:20.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_guess.guess_number scheduled__2023-02-28T03:35:00+00:00 [queued]>
[2024-05-23T17:50:20.391+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_guess.guess_number scheduled__2023-02-28T03:35:00+00:00 [queued]>
[2024-05-23T17:50:20.391+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-23T17:50:20.418+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): guess_number> on 2023-02-28 03:35:00+00:00
[2024-05-23T17:50:20.428+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2077) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T17:50:20.430+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xcom_guess', 'guess_number', 'scheduled__2023-02-28T03:35:00+00:00', '--job-id', '670', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmpruqbsf2m']
[2024-05-23T17:50:20.431+0000] {standard_task_runner.py:63} INFO - Started process 2084 to run task
[2024-05-23T17:50:20.431+0000] {standard_task_runner.py:91} INFO - Job 670: Subtask guess_number
[2024-05-23T17:50:20.455+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-23T17:50:20.516+0000] {task_command.py:426} INFO - Running <TaskInstance: xcom_guess.guess_number scheduled__2023-02-28T03:35:00+00:00 [running]> on host 88d46e04e9cd
[2024-05-23T17:50:20.685+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xcom_guess' AIRFLOW_CTX_TASK_ID='guess_number' AIRFLOW_CTX_EXECUTION_DATE='2023-02-28T03:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-28T03:35:00+00:00'
[2024-05-23T17:50:20.687+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T17:50:20.724+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T17:50:20.740+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sample_dag.py", line 19, in guess_number
    raise AirflowException(f"Wrong guess! Number: {number}, guess: {guess}")
airflow.exceptions.AirflowException: Wrong guess! Number: 9, guess: 2
[2024-05-23T17:50:20.748+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=xcom_guess, task_id=guess_number, run_id=scheduled__2023-02-28T03:35:00+00:00, execution_date=20230228T033500, start_date=20240523T175020, end_date=20240523T175020
[2024-05-23T17:50:20.792+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 670 for task guess_number (Wrong guess! Number: 9, guess: 2; 2084)
[2024-05-23T17:50:20.809+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T17:50:20.841+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T17:50:20.844+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
